version: '3.8'

services:
  app:
    build: .
    container_name: crm_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - crm-network

  db:
    image: postgres:15
    container_name: crm_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - crm-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: crm_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - crm-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  crm-network:
