services:
  app:
    build: .
    container_name: crm_app
    restart: on-failure
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      TZ: ${TZ}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - crm-network

  db:
    image: postgres:15.6-bookworm
    container_name: crm_postgres
    restart: always
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      POSTGRES_DB: ${POSTGRES_DB}         # <- назва бази, яку створить Postgres
      POSTGRES_USER: ${POSTGRES_USER}     # <- користувач
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # <- пароль
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crm-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: crm_pgadmin
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - crm-network

volumes:
  postgres-data:
  pgadmin-data:

networks:
  crm-network:
