spring:
  config:
    import: application-secret.properties

  application:
    name: CRM_v2_04_2025

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SECRET_DB_URL}
    username: ${SECRET_DB_USERNAME}
    password: ${SECRET_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        highlight_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: ${SECRET_DB_URL}
    user: ${SECRET_DB_USERNAME}
    password: ${SECRET_DB_PASSWORD}
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8080

jwt:
  expiration:
    time: 1
  secret:
    key: ${SECRET_JWT_KEY}