spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:crmdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        highlight_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:crmdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    user: sa
    password:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 8080

jwt:
  expiration:
    time: 1
  secret:
    key: iojgldfkg5uw405948MYKOLAfjlskjglj509483-05riupolgkjvnflkdja3-908u0
